/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cluedo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author Alumno
 */
public class panel extends javax.swing.JFrame {

   
   /* para que te lea los ficheros tienes que cambiar la ruta 
    donde los tienes guardados
    */
    
    
     private String nombres ="F:\\cluedo\\src\\archivos\\nombres.txt";
    private String armas  ="F:\\cluedo\\src\\archivos\\armas.txt";
    private String habitaciones="F:\\cluedo\\src\\archivos\\habitaciones.txt";
    
    /**
     * Creates new form panel
     */
    public panel() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        rellenarFich(nombres, selectorNombre);
        rellenarFich(armas,selectorArma);
        rellenarFich(habitaciones,selectorHabitacion);
        
        
    }

    
    private void rellenarFich (String fichero, JComboBox selector) throws IOException{
        
        LeerFichero fich = new LeerFichero(fichero);
        fich.readContent();
        String[] contenido = fich.getContent();
        
        for (int i=0; i < contenido.length; i++){
            selector.addItem(contenido[i]);
            
            
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        arma = new javax.swing.JLabel();
        habitacion = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaArma = new javax.swing.JTextField();
        cajaHabitacion = new javax.swing.JTextField();
        selectorNombre = new javax.swing.JComboBox<>();
        selectorArma = new javax.swing.JComboBox<>();
        selectorHabitacion = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        Aceptar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cajaAcusacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Cluedo");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(3, 3));

        nombre.setText("Nombre");
        jPanel3.add(nombre);

        arma.setText("Arma");
        jPanel3.add(arma);

        habitacion.setText("Habitación");
        jPanel3.add(habitacion);

        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        jPanel3.add(cajaNombre);
        jPanel3.add(cajaArma);
        jPanel3.add(cajaHabitacion);

        selectorNombre.setToolTipText("");
        selectorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorNombreActionPerformed(evt);
            }
        });
        jPanel3.add(selectorNombre);

        jPanel3.add(selectorArma);

        jPanel3.add(selectorHabitacion);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel4.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Acusación:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel5.add(cajaAcusacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 330, 30));

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        
        // añadimos al selector los campos que metemos en las cajas de texto
        String nombre = cajaNombre.getText();
        selectorNombre.addItem(nombre);
        
        
        String arma = cajaArma.getText();
        selectorArma.addItem(arma);
        
      
        
        String habitacion = cajaHabitacion.getText();
        selectorHabitacion.addItem(habitacion);
        
        
       
        //mostramos el contenido en la caja acusacion
        
        
        if ((cajaArma.getText().isEmpty()) || (cajaNombre.getText().isEmpty()) || cajaHabitacion.getText().isEmpty())
        {
            String cadenaNombre = (String) selectorNombre.getSelectedItem();
            
           
            String cadenaArma = (String) selectorArma.getSelectedItem();
            
            String cadenahabitacion = (String) selectorHabitacion.getSelectedItem();
            
            
            cajaAcusacion.setText(cadenaNombre + " ha muerto con un/a " + cadenaArma + 
             " en el/la " + cadenahabitacion);
            
            cajaNombre.setText("");
            cajaArma.setText("");
            cajaHabitacion.setText("");
        }
        
        
        
    }//GEN-LAST:event_AceptarActionPerformed

    
    private void selectorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new panel().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(panel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel arma;
    private javax.swing.JTextField cajaAcusacion;
    private javax.swing.JTextField cajaArma;
    private javax.swing.JTextField cajaHabitacion;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel habitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nombre;
    private javax.swing.JComboBox<String> selectorArma;
    private javax.swing.JComboBox<String> selectorHabitacion;
    private javax.swing.JComboBox<String> selectorNombre;
    // End of variables declaration//GEN-END:variables
}
